#!/bin/bash
chmod +x Iniciar
chmod +x Apagados/' Volver al principio'
chmod +x Apagados/'Apagar'
chmod +x Apagados/'Reinicar'
chmod +x Apagados/'Salir de sesion'
chmod +x Applets/' Volver al principio'
chmod +x Applets/'Abrir el reloj'
chmod +x Applets/'Ejecutar scrcpy'
chmod +x script/'Ejecutar applets '
chmod +x script/'Opciones de apagado '
chmod +x script/'Opciones de layout '
chmod +x layout/' Volver al principio'
chmod +x layout/'Floating'
chmod +x layout/'Fullscreen'
chmod +x layout/'Tiling'
chmod +x bspwm/'Aplicaciones.sh'
chmod +x bspwm/'Aplicaciones floating.sh'
chmod +x bspwm/'Aplicaciones tiled.sh'
chmod +x bspwm/'matapros.sh'
#BOLD="\e[1m"
#RED="\e[31m"
#BLUE="\e[34m"
#RESET="\e[0m"
#BACK_GREEN="\e[102m"
#BACK_YELLOW="\e[103m"
#BACK_GRAY="\e[100m"
cd /
cd usr/bin
sudo cp -r $HOME/.Rofi-menu/Spanish/rofi-menu .
chmod +x rofi-menu
ALG=0
echo -e "\e[100m\e[1m"
clear
echo -e "\e[100m    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐"
echo -e "\e[100m    │Escriba si, si tiene todos los paquetes instalados de la esta lista y no, si no tiene alguno o ninguno:     │"
echo -e "\e[100m    │tty-clock, rofi, scrcpy, hack-nerd-fonts                                                                    │"
echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
echo -e "\e[100m     "
while [ $ALG == 0 ]; do

read input
if [ $input == si ]; then
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌─────┐"
	echo -e "\e[100m    │Adios│"
	echo -e "\e[100m    └─────┘"
	clear
	sleep 1
	break
elif [ $input == no ]; then
	echo -e "\e[100m\e[1m"
	clear
	pacman -S rofi --noconfirm
	yay -S tty-clock --noconfirm
	yay -S scrcpy --noconfirm
	yay -S nerd-fonts-hack --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌───────────────────────────────────────────┐"
	echo -e "\e[100m    │Se han instalado los paquetes correctamente│"
	echo -e "\e[100m    └───────────────────────────────────────────┘"
	sleep 0.5
	echo -e "\e[100m    ┌─────┐"
	echo -e "\e[100m    │Adios│"
	echo -e "\e[100m    └─────┘"
	sleep 2
	clear
	break
	
else 
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌──────────────────────────────────────────────────────────────────────────────┐"
	echo -e "\e[100m    │\e[31mDebe de escribir si si tene todos los paquetes y no sin no tiene uno o ninguno\e[0m\e[100m\e[1m│"
	echo -e "\e[100m    └──────────────────────────────────────────────────────────────────────────────┘"
	echo -e "\e[100m    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐"
	echo -e "\e[100m    │Escriba si, si tiene todos los paquetes instalados de la esta lista y no, si no tiene alguno o ninguno:     │"
	echo -e "\e[100m    │tty-clock, rofi, scrcpy, hack-nerd-fonts                                                                    │"
	echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
	echo -e "\e[100m     "
	fi
	
	case $ALG in

	esac
	done


