#!/bin/bash
#BOLD="\e[1m"
#RED="\e[31m"
#BLUE="\e[34m"
#RESET="\e[0m"
#BACK_GREEN="\e[102m"
#BACK_YELLOW="\e[103m"
#BACK_GRAY="\e[100m"
function help {
        echo -e "    \e[100m\e[1m\e[31m┌──────────────────────────────────────────────┐\e[0m"
        echo -e "    \e[100m\e[1m\e[31m│-e  --english  Install rofi-menu in english   │\e[0m"
        echo -e "    \e[100m\e[1m\e[31m│-s  --spanish  Install rofi-menu in spanish   │\e[0m"
	echo -e "    \e[100m\e[1m\e[31m│don't install this program in your HOME folder│\e[0m"
        echo -e "    \e[100m\e[1m\e[31m└──────────────────────────────────────────────┘\e[0m"
}
function us {
chmod +x 'lenguaje english'
./'lenguaje english'
}
function es {
chmod +x 'lenguaje espanol'
./'lenguaje espanol'
}
promt=$1
	if [[ $1 == "--help" ]]; then
	help
	elif [[ $1 == "-h" ]]; then
	help
	elif [[ $1 == "-e" ]]; then
	us
	elif [[ $1 == "--english" ]]; then
	us
	elif [[ $1 == "-s" ]]; then
	es
	elif [[ $1 == "--spanish" ]]; then
	es
	elif [[ -z $p ]]; then
	help
	else
	help
	fi

