#!/bin/bash
chmod +x Iniciar
chmod +x bspwm/'Aplicaciones.sh'
chmod +x bspwm/'Aplicaciones floating.sh'
chmod +x bspwm/'Aplicaciones tiled.sh'
chmod +x bspwm/'matapros.sh'
chmod +x dmenu/Iniciar
chmod +x dmenu/bspwm/'Aplicaciones.sh'
chmod +x dmenu/bspwm/'Aplicaciones floating.sh'
chmod +x dmenu/bspwm/'Aplicaciones tiled.sh'
chmod +x dmenu/bspwm/'matapros.sh'
chmod +x fancy/Iniciar
chmod +x fancy/bspwm/'Aplicaciones.sh'
chmod +x fancy/bspwm/'Aplicaciones floating.sh'
chmod +x fancy/bspwm/'Aplicaciones tiled.sh'
chmod +x fancy/bspwm/'matapros.sh'
#BOLD="\e[1m"
#RED="\e[31m"
#BLUE="\e[34m"
#RESET="\e[0m"
#BACK_GREEN="\e[102m"
#BACK_YELLOW="\e[103m"
#BACK_GRAY="\e[100m"
cd /
cd usr/bin
sudo cp -r $HOME/.Rofi-menu/Spanish/rofi-menu .
sudo chmod +x rofi-menu
ALG=0
echo -e "\e[100m\e[1m"
clear
echo -e "\e[100m    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐"
echo -e "\e[100m    │Escriba si, si tiene todos los paquetes instalados de la esta lista y no, si no tiene alguno o ninguno:     │"
echo -e "\e[100m    │tty-clock-git, rofi, scrcpy, hack-nerd-fonts                                                                │"
echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
echo -e "\e[100m     "
while [ $ALG == 0 ]; do

read input
if [ $input == si ]; then
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌─────┐"
	echo -e "\e[100m    │Adios│"
	echo -e "\e[100m    └─────┘"
	clear
	sleep 1
	break
elif [ $input == no ]; then
	echo -e "\e[100m\e[1m"
	clear
	sudo pacman -S rofi --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	yay -S tty-clock-git --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	yay -S scrcpy --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	yay -S nerd-fonts-hack --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌───────────────────────────────────────────┐"
	echo -e "\e[100m    │Se han instalado los paquetes correctamente│"
	echo -e "\e[100m    └───────────────────────────────────────────┘"
	sleep 0.5
	echo -e "\e[100m    ┌─────┐"
	echo -e "\e[100m    │Adios│"
	echo -e "\e[100m    └─────┘"
	sleep 2
	clear
	break
	
else 
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌──────────────────────────────────────────────────────────────────────────────┐"
	echo -e "\e[100m    │\e[31mDebe de escribir si si tene todos los paquetes y no sin no tiene uno o ninguno\e[0m\e[100m\e[1m│"
	echo -e "\e[100m    └──────────────────────────────────────────────────────────────────────────────┘"
	echo -e "\e[100m    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐"
	echo -e "\e[100m    │Escriba si, si tiene todos los paquetes instalados de la esta lista y no, si no tiene alguno o ninguno:     │"
	echo -e "\e[100m    │tty-clock-git, rofi, scrcpy, hack-nerd-fonts                                                                │"
	echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
	echo -e "\e[100m     "
	fi
	
	case $ALG in

	esac
	done


