#!/bin/bash
chmod +x Iniciar
chmod +x Apagados/' Volver al principio'
chmod +x Apagados/'Apagar'
chmod +x Apagados/'Reinicar'
chmod +x Apagados/'Salir de sesion'
chmod +x Applets/' Volver al principio'
chmod +x Applets/'Abrir el reloj'
chmod +x Applets/'Ejecutar scrcpy'
chmod +x script/'Ejecutar applets '
chmod +x script/'Opciones de apagado '
chmod +x script/'Opciones de layout '
chmod +x layout/' Volver al principio'
chmod +x layout/'Floating'
chmod +x layout/'Fullscreen'
chmod +x layout/'Tiling'
chmod +x bspwm/'Aplicaciones.sh'
chmod +x bspwm/'Aplicaciones floating.sh'
chmod +x bspwm/'Aplicaciones tiled.sh'
chmod +x bspwm/'matapros.sh'
echo "Escriba 1) Si, si tiene todos los paquetes instalados de la esta lista y 2) No, si no tiene alguno o ninguno"
PS3="tty-clock, rofi, scrcpy, hack-nerd-fonts: "
select escribir in Si No
do
	case $escribir in

	No)
	clear
	sudo pacman -S rofi --noconfirm
	yay -S tty-clock --noconfirm
	yay -S scrcpy --noconfirm
	yay -S nerd-fonts-hack
	clear
	echo "De favor sete como fuente principal las hack nerd fonts "
	echo "Esa ventana se serrara en 5"
	sleep 1
	echo "Esa ventana se serrara en 4"
	sleep 1
	echo "Esa ventana se serrara en 3"
	sleep 1
	echo "Esa ventana se serrara en 2"
	sleep 1
	echo "Esa ventana se serrara en 1"
	sleep 1
	break
	;;
	
	Si)
	clear
	echo "Adios"
	sleep 1
	break
	;;
	
	*)
	echo "Selecciona una opcion"
	;;
	
	esac
done


