#!/bin/bash
echo "Escribe la ruta exacta de de donde esta la carpeta Rofi-menu-final:"
read input
echo "cd $input" >> Iniciar
echo 'ls script | rofi -show -dmenu -theme "/usr/share/rofi/themes/sidebar.rasi" -font "Hack Nerd Font 15" -i | xargs -I_ bash script/_' >> Iniciar
