#!/bin/bash
echo "Escribe la ruta exacta de de donde esta la carpeta Rofi-menu-final:"
read input
echo "cd $input" >> Iniciar
echo 'ls script | rofi -show -dmenu -theme "/usr/share/rofi/themes/sidebar.rasi" -font "Hack Nerd Font 15" -i | xargs -I_ bash script/_' >> Iniciar
clear
PS3="Selecciona la terminal que usas: "

select terminal in Konsole Tilix Gnome-Terminal Terminator Alacritty 
do
		case $terminal in		
		
		Konsole)
			echo 'konsole -e tty-clock' >> Applets/'Abrir el reloj '
			echo "Se ha seteado satisfactoriamente"
			break
		;;
		
		Tilix)
			echo 'tilix -e tty-clock' >> Applets/'Abrir el reloj '
			echo "Se ha seteado satisfactoriamente"
			break
		;;
		
		Gnome-Terminal)
			echo 'gnome-terminal -e tty-clock' >> Applets/'Abrir el reloj '
			echo "Se ha seteado satisfactoriamente"
			break
		;;
		
		Terminator)
			echo 'terminator -e tty-clock' >> Applets/'Abrir el reloj '
			echo "Se ha seteado satisfactoriamente"
			break
		;;
		
		Alacritty)
			echo 'alacritty -e tty-clock' >> Applets/'Abrir el reloj '
			echo "Se ha seteado satisfactoriamente"
			break
		;;
			
	esac
done
		
			
			
