#!/bin/bash
chmod +x Iniciar
chmod +x dmenu/Iniciar
chmod +x fancy/Iniciar
#BOLD="\e[1m"
#RED="\e[31m"
#BLUE="\e[34m"
#RESET="\e[0m"
#BACK_GREEN="\e[102m"
#BACK_YELLOW="\e[103m"
#BACK_GRAY="\e[100m"
cd /
cd usr/bin
sudo cp -r $HOME/.Rofi-menu/English/rofi-menu .
sudo chmod +x rofi-menu
ALG=0
echo -e "\e[100m\e[1m"
clear       
echo -e "\e[100m     ┌─────────────────────────────┐"
echo -e "\e[100m     │Select your favorite terminal│"
echo -e "\e[100m    ┌┴─────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┐"
echo -e "\e[100m    │Type yes, if you have all the packages installed from this list and no, if you don't have any or none:      │"
echo -e "\e[100m    │tty-clock-git, rofi, scrcpy, hack-nerd-fonts                                                                │"
echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
echo -e "\e[100m     "
while [ $ALG == 0 ]; do
echo -e "\e[100m\e[1m"
read input
if [ $input == yes ]; then
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌────────┐"
	echo -e "\e[100m    │Good bye│"
	echo -e "\e[100m    └────────┘"
	clear
	sleep 1
	break
elif [ $input == no ]; then
	echo -e "\e[100m\e[1m"
	clear
	sudo pacman -S yay --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	sudo pacman -S rofi --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	yay -S tty-clock-git --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	yay -S scrcpy --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	yay -S nerd-fonts-hack --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌──────────────────────────────────────┐"
	echo -e "\e[100m    │Packages have been installed correctly│"
	echo -e "\e[100m    └──────────────────────────────────────┘"
	sleep 0.5
	echo -e "\e[100m    ┌────────┐"
	echo -e "\e[100m    │Good bye│"
	echo -e "\e[100m    └────────┘"
	sleep 2
	clear
	break
	
else 
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌──────────────────────────────────────────────────────────────────────────────────┐"   
	echo -e "\e[100m    │\e[31mYou must write if you have all the packages and not if you do not have one or none\e[0m\e[100m\e[1m│"
	echo -e "\e[100m    └──────────────────────────────────────────────────────────────────────────────────┘"   
	echo -e "\e[100m     ┌─────────────────────────────┐"
	echo -e "\e[100m     │Select your favorite terminal│"
	echo -e "\e[100m    ┌┴─────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┐"
	echo -e "\e[100m    │Type yes, if you have all the packages installed from this list and no, if you don't have any or none:      │"
	echo -e "\e[100m    │tty-clock-git, rofi, scrcpy, hack-nerd-fonts                                                                │"
	echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
	echo -e "\e[100m     "
	fi
	
	case $ALG in

	esac
	done


