#!/bin/bash
chmod +x Iniciar
chmod +x Apagados/' Back to the top'
chmod +x Apagados/'Power off'
chmod +x Apagados/'Reboot'
chmod +x Apagados/'Exit from session'
chmod +x Applets/' Back to the top'
chmod +x Applets/'Open the watch'
chmod +x Applets/'Execute scrcpy'
chmod +x script/'Execute applets '
chmod +x script/'Options from power off '
chmod +x script/'Options from layout '
chmod +x layout/' Back to the top'
chmod +x layout/'Floating'
chmod +x layout/'Fullscreen'
chmod +x layout/'Tiling'
chmod +x bspwm/'Aplicaciones.sh'
chmod +x bspwm/'Aplicaciones floating.sh'
chmod +x bspwm/'Aplicaciones tiled.sh'
chmod +x bspwm/'matapros.sh'

#BOLD="\e[1m"
#RED="\e[31m"
#BLUE="\e[34m"
#RESET="\e[0m"
#BACK_GREEN="\e[102m"
#BACK_YELLOW="\e[103m"
#BACK_GRAY="\e[100m"
cd /
cd usr/bin
sudo cp -r $HOME/.Rofi-menu/English/rofi-menu .
sudo chmod +x rofi-menu
ALG=0
echo -e "\e[100m\e[1m"
clear
echo -e "\e[100m    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐"
echo -e "\e[100m    │Type yes, if you have all the packages installed from this list and no, if you have none or none at all:    │"
echo -e "\e[100m    │tty-clock, rofi, scrcpy, hack-nerd-fonts                                                                    │"
echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
echo -e "\e[100m     "
while [ $ALG == 0 ]; do

read input
if [ $input == yes ]; then
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌────────┐"
	echo -e "\e[100m    │Good bye│"
	echo -e "\e[100m    └────────┘"
	clear
	sleep 1
	break
elif [ $input == no ]; then
	echo -e "\e[100m\e[1m"
	clear
	sudo pacman -S rofi --noconfirm
	yay -S tty-clock --noconfirm
	yay -S scrcpy --noconfirm
	yay -S nerd-fonts-hack --noconfirm
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌──────────────────────────────────────┐"
	echo -e "\e[100m    │Packages have been installed correctly│"
	echo -e "\e[100m    └──────────────────────────────────────┘"
	sleep 0.5
	echo -e "\e[100m    ┌────────┐"
	echo -e "\e[100m    │Good bye│"
	echo -e "\e[100m    └────────┘"
	sleep 2
	clear
	break
	
else 
	echo -e "\e[100m\e[1m"
	clear
	echo -e "\e[100m    ┌──────────────────────────────────────────────────────────────────────────────────┐"   
	echo -e "\e[100m    │\e[31mYou must write if you have all the packages and not if you do not have one or none\e[0m\e[100m\e[1m│"
	echo -e "\e[100m    └──────────────────────────────────────────────────────────────────────────────────┘"   
	echo -e "\e[100m    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐"
	echo -e "\e[100m    │Type yes, if you have all the packages installed from this list and no, if you have none or none at all:    │"
	echo -e "\e[100m    │tty-clock, rofi, scrcpy, hack-nerd-fonts                                                                    │"
	echo -e "\e[100m    └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
	echo -e "\e[100m     "
	fi
	
	case $ALG in

	esac
	done


