#!/bin/bash
#BOLD="\e[1m"
#RED="\e[31m"
#BLUE="\e[34m"
#RESET="\e[0m"
#BACK_GREEN="\e[102m"
#BACK_YELLOW="\e[103m"
#BACK_GRAY="\e[100m"
ALG=0
echo -e "\e[1m"
clear
echo -e "\e[1;30m    \e[1;44m┌─────────────────────────────┐\e[0m"
echo -e "\e[1;30m    \e[1;44m│\e[31mRofi Menu Installation Wizard\e[0m\e[1;44m\e[1;30m│\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m├─────────────────────────────┤\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│Select your favorite terminal│\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m└─────────────────────────────┘\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m┌─────────────────────────────┐\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│1) Konsole                   │\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│2) Tilix                     │\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│3) Gnome Terminal            │\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│4) Terminator                │\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│5) Alacritty                 │\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m│6) Xfce Terminal             │\e[100m \e[0m"
echo -e "\e[1;30m    \e[1;44m└─────────────────────────────┘\e[100m \e[0m"
echo -e "\e[1;30m     \e[100m                               \e[0m"
echo -e "     \e[0m"
while [ $ALG == 0 ]; do
echo -e "\e[1m"
read input2
if [ $input2 == 1 ]; then
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌──────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│Thanks for your choice│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└──────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                        \e[0m"
	sleep 0.5
	echo 'konsole -e tty-clock &' >> Applets/'Open the watch'
	echo 'konsole -e tty-clock &' >> dmenu/Applets/'Open the watch'
	echo 'konsole -e tty-clock &' >> fancy/Applets/'Open the watch'
	echo 'konsole -e ./hist' >> Applets/'Consult the shell history'
	echo 'konsole -e ./hist' >> dmenu/Applets/'Consult the shell history'
	echo 'konsole -e ./hist' >> fancy/Applets/'Consult the shell history'
	sleep 1
	chmod +x Dependencias
	./Dependencias
	break
		
elif [ $input2 == 2 ]; then
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌──────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│Thanks for your choice│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└──────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                        \e[0m"
	sleep 0.5
	echo 'tilix -e tty-clock &' >> Applets/'Open the watch'
	echo 'tilix -e tty-clock &' >> dmenu/Applets/'Open the watch'
	echo 'tilix -e tty-clock &' >> fancy/Applets/'Open the watch'
	echo 'tilix -e ./hist' >> Applets/'Consult the shell history'
	echo 'tilix -e ./hist' >> dmenu/Applets/'Consult the shell history'
	echo 'tilix -e ./hist' >> fancy/Applets/'Consult the shell history'
	chmod +x Dependencias
	./Dependencias
	break
		
elif [ $input2 == 3 ]; then
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌──────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│Thanks for your choice│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└──────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                        \e[0m"
	sleep 0.5
	echo 'gnome-terminal -e tty-clock &' >> Applets/'Open the watch'
	echo 'gnome-terminal -e tty-clock &' >> dmenu/Applets/'Open the watch'
	echo 'gnome-terminal -e tty-clock &' >> fancy/Applets/'Open the watch'
	echo 'gnome-terminal -e ./hist' >> Applets/'Consult the shell history'
	echo 'gnome-terminal -e ./hist' >> dmenu/Applets/'Consult the shell history'
	echo 'gnome-terminal -e ./hist' >> fancy/Applets/'Consult the shell history'
	sleep 1
	chmod +x Dependencias
	./Dependencias
	break
		
elif [ $input2 == 4 ]; then
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌──────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│Thanks for your choice│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└──────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                        \e[0m"
	sleep 0.5
	echo 'terminator -e tty-clock &' >> Applets/'Open the watch'
	echo 'terminator -e tty-clock &' >> dmenu/Applets/'Open the watch'
	echo 'terminator -e tty-clock &' >> fancy/Applets/'Open the watch'
	echo 'terminator -e ./hist' >> Applets/'Consult the shell history'
	echo 'terminator -e ./hist' >> dmenu/Applets/'Consult the shell history'
	echo 'terminator -e ./hist' >> fancy/Applets/'Consult the shell history'
	sleep 1
	chmod +x Dependencias
	./Dependencias
	break
		
elif [ $input2 == 4 ]; then
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌──────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│Thanks for your choice│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└──────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                        \e[0m"
	sleep 0.5
	echo 'xfce4-terminal -e tty-clock &' >> Applets/'Open the watch'
	echo 'xfce4-terminal -e tty-clock &' >> dmenu/Applets/'Open the watch'
	echo 'xfce4-terminal -e tty-clock &' >> fancy/Applets/'Open the watch'
	echo 'xfce4-terminal -e ./hist' >> Applets/'Consult the shell history'
	echo 'xfce4-terminal -e ./hist' >> dmenu/Applets/'Consult the shell history'
	echo 'xfce4-terminal -e ./hist' >> fancy/Applets/'Consult the shell history'
	sleep 1
	chmod +x Dependencias
	./Dependencias
	break

elif [ $input2 == 4 ]; then
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌──────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│Thanks for your choice│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└──────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                        \e[0m"
	sleep 0.5
	echo 'alacritty -e tty-clock &' >> Applets/'Open the watch'
	echo 'alacritty -e tty-clock &' >> dmenu/Applets/'Open the watch'
	echo 'alacritty -e tty-clock &' >> fancy/Applets/'Open the watch'
	echo 'alacritty -e ./hist' >> Applets/'Consult the shell history'
	echo 'alacritty -e ./hist' >> dmenu/Applets/'Consult the shell history'
	echo 'alacritty -e ./hist' >> fancy/Applets/'Consult the shell history'
	sleep 1
	chmod +x Dependencias
	./Dependencias
	break
else 
echo -e "\e[1m"
clear
	echo -e "\e[1;30m    \e[1;44m┌─────────────────────────────────────────────────────┐\e[0m" 
	echo -e "\e[1;30m    \e[1;44m│\e[31mChoose your favorite terminal by typing these numbers\e[0m\e[1;30m\e[1;44m\e[1m│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└─────────────────────────────────────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                                                       \e[0m"
	echo -e " "
	echo -e "\e[1;30m    \e[1;44m┌─────────────────────────────┐\e[0m"
	echo -e "\e[1;30m    \e[1;44m│\e[31mRofi Menu Installation Wizard\e[0m\e[1;44m\e[1;30m│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m├─────────────────────────────┤\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│Select your favorite terminal│\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└─────────────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m┌─────────────────────────────┐\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│1) Konsole                   │\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│2) Tilix                     │\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│3) Gnome Terminal            │\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│4) Terminator                │\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│5) Alacritty                 │\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m│6) Xfce Terminal             │\e[100m \e[0m"
	echo -e "\e[1;30m    \e[1;44m└─────────────────────────────┘\e[100m \e[0m"
	echo -e "\e[1;30m     \e[100m                               \e[0m"
	echo -e "     \e[0m"
	fi
	case $ALG in
	
esac
done
		
			
			
