#!/bin/bash
cd $HOME
cd .Rofi-menu/English
function help {
        echo -e "    \e[1;46m\e[1m\e[31m┌──────────[HELP]──────────┐\e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m│\e[35m-h --help\e[0m\e[1;46m\e[1m\e[31m   this window   │\e[100m \e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m│\e[35m-n\e[0m\e[1;46m\e[1m\e[31m   normal theme         │\e[100m \e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m│\e[35m-f\e[0m\e[1;46m\e[1m\e[31m   fancy theme          │\e[100m \e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m│\e[35m-d\e[0m\e[1;46m\e[1m\e[31m   dmenu theme          │\e[100m \e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m│\e[35m-u\e[0m\e[1;46m\e[1m\e[31m   uninstall rofi-menu  │\e[100m \e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m│\e[35m-up\e[0m\e[1;46m\e[1m\e[31m   update rofi-menu    │\e[100m \e[0m"
        echo -e "    \e[1;46m\e[1m\e[31m└──────────[V1.2]──────────┘\e[100m \e[0m"
        echo -e "     \e[100m                            \e[0m"
}
prompt=$1
        if [[ $1 == --help ]]; then
        help
        elif [[ $1 == -h ]]; then
        help
        elif [[ $1 == -n ]]; then
        ./Iniciar
        elif [[ $1 == -f ]]; then
        cd fancy
        ./Iniciar
        elif [[ $1 == -d ]]; then
        cd dmenu
        ./Iniciar
        elif [[ $1 == -u ]]; then
        chmod +x Des
        ./Des
        elif [[ $1 == -up ]]; then
        sudo pacman -Syu --noconfirm
        yay -Syu --noconfirm
        sudo rm -r $HOME/upt-rofi; git clone https://github.com/LBY-L/Rofi-menu $HOME/upt-rofi; cd $HOME/upt-rofi; chmod +x Install; ./Install -e
        elif [[ -z $1 ]]; then
        help
        else
        help
        fi

