#!/bin/bash
cd $HOME
cd .Rofi-menu/English
function help {
        echo -e "    \e[1;44m\e[1m\e[30m┌──────────[\e[31mHELP\e[0m\e[1;44m\e[1m\e[30m]──────────┐\e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m│\e[37m-h --help\e[0m\e[1;44m\e[1m\e[30m   this window   │\e[100m \e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m│\e[37m-n\e[0m\e[1;44m\e[1m\e[30m   normal theme         │\e[100m \e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m│\e[37m-f\e[0m\e[1;44m\e[1m\e[30m   fancy theme          │\e[100m \e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m│\e[37m-d\e[0m\e[1;44m\e[1m\e[30m   dmenu theme          │\e[100m \e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m│\e[37m-u\e[0m\e[1;44m\e[1m\e[30m   uninstall rofi-menu  │\e[100m \e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m│\e[37m-up\e[0m\e[1;44m\e[1m\e[30m   update rofi-menu    │\e[100m \e[0m"
        echo -e "    \e[1;44m\e[1m\e[30m└──────────[\e[31mV1.3\e[0m\e[1;44m\e[1m\e[30m]──────────┘\e[100m \e[0m"
        echo -e "     \e[100m                            \e[0m"
}
prompt=$1
        if [[ $1 == --help ]]; then
        help
        elif [[ $1 == -h ]]; then
        help
        elif [[ $1 == -n ]]; then
        ./Iniciar
        elif [[ $1 == -f ]]; then
        cd fancy
        ./Iniciar
        elif [[ $1 == -d ]]; then
        cd dmenu
        ./Iniciar
        elif [[ $1 == -u ]]; then
        chmod +x Des
        ./Des
        elif [[ $1 == -up ]]; then
        sudo pacman -Syu --noconfirm
        yay -Syu --noconfirm
        sudo rm -r $HOME/upt-rofi; git clone https://github.com/LBY-L/Rofi-menu $HOME/upt-rofi; cd $HOME/upt-rofi; chmod +x Install; ./Install -e
        elif [[ -z $1 ]]; then
        help
        else
        help
        fi

